from turtle import *
colours = {'noice orange': '#D53F0A',
           'limely': '#A7E30E' }
screen = Screen()
screen.setup(1000,600)
screen.bgcolor(colours['noice orange'])
color('#000000')
pensize(5)
penup()
goto(-150,130)
pendown()
speed(3)
begin_fill()
fillcolor('red')
for s in range(4):
    forward(300)
    right(90)
end_fill()
penup()
goto(0,0)
pendown()
color(colours['limely'])
style = ('Verdana', 45,"bold")
write('HELLO', font=style, align='center')
penup()
right(90)
forward(60)
pendown()
color("#FFCC00")
write('GILES', font=style, align='center')
penup()
goto(110,-3)
pendown()
right(78)
forward(220)
right(102)
penup()
forward(45)
right(102)
pendown()
forward(220)
penup()
goto(0,-120)
color("#0033CC")
write('CLOWN',font=style, align='center')
exitonclick()


